/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/interview/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_api_interview_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/interview/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat Stream */
        post: operations["chat_stream_api_interview_chat_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/interview/system-prompt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** System Prompt */
        post: operations["system_prompt_api_interview_system_prompt_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Config */
        get: operations["get_config_api_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cv/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Parse Cv */
        post: operations["parse_cv_api_cv_parse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/interview/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Plan */
        post: operations["create_plan_api_interview_plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/interview/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Feedback */
        post: operations["create_feedback_api_interview_feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Presets */
        get: operations["get_presets_api_presets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voice/transcribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transcribe Answer */
        post: operations["transcribe_answer_api_voice_transcribe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voice/speak": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Speak Sentence */
        post: operations["speak_sentence_api_voice_speak_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnswerEvaluation */
        AnswerEvaluation: {
            /** Question */
            question: number;
            /** Topic */
            topic: string;
            /** Asked */
            asked: string;
            /** Criteria */
            criteria: components["schemas"]["CriterionScore"][];
            /** Score */
            score: number;
            /** Feedback */
            feedback: string;
        };
        /** AnsweredQuestion */
        AnsweredQuestion: {
            /** Question */
            question: number;
            /** Exchanges */
            exchanges: components["schemas"]["Exchange"][];
        };
        /** AppConfig */
        AppConfig: {
            /** Models */
            models: components["schemas"]["ModelInfo"][];
            /** Default Model */
            default_model: string;
            /** Techniques */
            techniques: ("zero_shot" | "few_shot" | "chain_of_thought" | "persona" | "self_critique")[];
            /**
             * Default Technique
             * @enum {string}
             */
            default_technique: "zero_shot" | "few_shot" | "chain_of_thought" | "persona" | "self_critique";
            /** Companies */
            companies: ("Guugle" | "HeadBook" | "Instakilogram" | "Netflux" | "Amazin" | "Goldman Sax" | "Tesler" | "Starbacks")[];
            /** Interviewers */
            interviewers: {
                [key: string]: string;
            };
            /** Difficulties */
            difficulties: ("easy" | "medium" | "hard")[];
            /** Personas */
            personas: ("friendly" | "neutral" | "strict")[];
            default_settings: components["schemas"]["InterviewSettings"];
            default_model_settings: components["schemas"]["ModelSettings"];
            /** Max Tokens Range */
            max_tokens_range: [
                number,
                number
            ];
            /** Question Count Range */
            question_count_range: [
                number,
                number
            ];
            /** Session Cost Cap Usd */
            session_cost_cap_usd: number;
        };
        /** Body_parse_cv_api_cv_parse_post */
        Body_parse_cv_api_cv_parse_post: {
            /** File */
            file: string;
        };
        /** CandidateProfile */
        CandidateProfile: {
            /**
             * First Name
             * @description First name only, null if not found
             */
            first_name: string | null;
            /**
             * Headline
             * @description One line: profession, years, focus
             */
            headline: string;
            /**
             * Seniority
             * @description Level in the candidate's own field, not in the job they apply for
             * @enum {string}
             */
            seniority: "junior" | "mid" | "senior" | "lead";
            /**
             * Years Experience
             * @description Total years of work experience, from the job periods. Null only if no dates
             */
            years_experience: number | null;
            /** Skills */
            skills: string[];
            /**
             * Experience
             * @description Newest first
             */
            experience: components["schemas"]["Experience"][];
            /** Education */
            education: string[];
            /**
             * Interview Topics
             * @description Concrete things from this CV an interviewer could ask about
             */
            interview_topics: string[];
        };
        /** ChatMessage */
        ChatMessage: {
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Content */
            content: string;
        };
        /** ChatRequest */
        ChatRequest: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Messages */
            messages: components["schemas"]["ChatMessage"][];
            settings?: components["schemas"]["InterviewSettings"];
            /**
             * System Prompt
             * @default zero_shot
             * @enum {string}
             */
            system_prompt: "zero_shot" | "few_shot" | "chain_of_thought" | "persona" | "self_critique";
            model_settings?: components["schemas"]["ModelSettings"];
            plan?: components["schemas"]["SignedPlan-Input"] | null;
            progress?: components["schemas"]["PlanProgress"] | null;
            /** History Signature */
            history_signature?: string | null;
        };
        /** ChatResponse */
        ChatResponse: {
            /** Reply */
            reply: string;
            /** Blocked */
            blocked?: ("message" | "role" | "guard_error" | "leak") | null;
            /** Hint */
            hint?: ("end" | "off_topic" | "not_answered") | null;
            /** Ended */
            ended?: ("candidate_left" | "limit_reached" | "completed") | null;
            progress?: components["schemas"]["PlanProgress"] | null;
            guard?: components["schemas"]["GuardVerdict"] | null;
            /** History Signature */
            history_signature?: string | null;
        };
        /** CriterionScore */
        CriterionScore: {
            /** Criterion */
            criterion: string;
            /** Met */
            met: number;
            /** Score */
            score: number;
        };
        /** Exchange */
        Exchange: {
            /** Interviewer */
            interviewer: string;
            /** Candidate */
            candidate: string;
        };
        /** Experience */
        Experience: {
            /**
             * Title
             * @description Job title as written in the CV
             */
            title: string;
            /** Company */
            company: string;
            /**
             * Period
             * @description As written in the CV, e.g. "2021 – present"
             */
            period: string;
            /**
             * Highlights
             * @description Up to 3 short achievements, only facts from the CV
             */
            highlights: string[];
        };
        /** FeedbackRequest */
        FeedbackRequest: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            settings: components["schemas"]["InterviewSettings"];
            plan: components["schemas"]["SignedPlan-Input"];
            /** Answers */
            answers: components["schemas"]["AnsweredQuestion"][];
        };
        /** FeedbackResponse */
        FeedbackResponse: {
            /** Evaluations */
            evaluations: components["schemas"]["AnswerEvaluation"][];
            scorecard: components["schemas"]["Scorecard"];
        };
        /** GuardVerdict */
        GuardVerdict: {
            /** Category */
            category?: ("ok" | "off_topic" | "injection" | "abuse") | null;
            /** Probabilities */
            probabilities?: {
                [key: string]: number;
            };
            /** Role Injection */
            role_injection?: number | null;
            /** Blocked */
            blocked?: ("message" | "role" | "guard_error" | "leak") | null;
            /** Answered */
            answered?: number | null;
            /** Vague */
            vague?: number | null;
            /** Wants To End */
            wants_to_end?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InterviewPlan */
        InterviewPlan: {
            /**
             * Approach
             * @description One line, e.g. "Career changer: focus on motivation and transferable skills"
             */
            approach: string;
            /** Questions */
            questions: components["schemas"]["PlannedQuestion"][];
        };
        /** InterviewSettings */
        InterviewSettings: {
            /**
             * Company
             * @default Guugle
             * @enum {string}
             */
            company: "Guugle" | "HeadBook" | "Instakilogram" | "Netflux" | "Amazin" | "Goldman Sax" | "Tesler" | "Starbacks";
            /**
             * Role
             * @default Software Engineer
             */
            role: string;
            /**
             * Difficulty
             * @default medium
             * @enum {string}
             */
            difficulty: "easy" | "medium" | "hard";
            /**
             * Persona
             * @default friendly
             * @enum {string}
             */
            persona: "friendly" | "neutral" | "strict";
            /**
             * Question Count
             * @default 5
             */
            question_count: number;
        };
        /** ModelInfo */
        ModelInfo: {
            /** Id */
            id: string;
            /** Name */
            name?: string | null;
            /** Input Price Per M */
            input_price_per_m?: number | null;
            /** Output Price Per M */
            output_price_per_m?: number | null;
            /** Supported Parameters */
            supported_parameters?: string[] | null;
            /** Reasoning Efforts */
            reasoning_efforts?: string[] | null;
        };
        /** ModelSettings */
        ModelSettings: {
            /** Model */
            model?: string | null;
            /**
             * Reasoning Effort
             * @default minimal
             * @enum {string}
             */
            reasoning_effort: "minimal" | "low" | "medium" | "high";
            /**
             * Max Tokens
             * @default 1000
             */
            max_tokens: number;
        };
        /** PlanProgress */
        PlanProgress: {
            /**
             * Question
             * @default 0
             */
            question: number;
            /**
             * Extra Turns
             * @default 0
             */
            extra_turns: number;
        };
        /** PlanRequest */
        PlanRequest: {
            settings?: components["schemas"]["InterviewSettings"];
            profile?: components["schemas"]["CandidateProfile"] | null;
            /** Job Description */
            job_description?: string | null;
        };
        /** PlannedQuestion */
        PlannedQuestion: {
            /**
             * Type
             * @enum {string}
             */
            type: "motivation" | "experience" | "behavioural" | "technical" | "situational";
            /**
             * Topic
             * @description Short label, e.g. "event streaming at Spotifly"
             */
            topic: string;
            /**
             * Question
             * @description The core question. The interviewer phrases it in its own words
             */
            question: string;
            /**
             * Why
             * @description One sentence, e.g. "The job description asks for Kafka, the CV shows Kafka"
             */
            why: string;
            /**
             * Rubric
             * @description Yes/no statements a good answer meets, e.g. "Gives a concrete example"
             */
            rubric: string[];
        };
        /** Preset */
        Preset: {
            /** Id */
            id: string;
            settings: components["schemas"]["InterviewSettings"];
            /** Job Description */
            job_description: string;
            profile: components["schemas"]["CandidateProfile"];
            /** Cv File */
            cv_file: string;
        };
        /** Scorecard */
        Scorecard: {
            /** Overall */
            overall: number;
            /** Answered */
            answered: number;
            /** Total */
            total: number;
            /** Strengths */
            strengths: string[];
            /** Improvements */
            improvements: string[];
            /** Weakest Question */
            weakest_question: number;
            /** Sample Answer */
            sample_answer: string;
        };
        /** SignedPlan */
        "SignedPlan-Input": {
            plan: components["schemas"]["InterviewPlan"];
            /** Signature */
            signature: string;
        };
        /** SignedPlan */
        "SignedPlan-Output": {
            plan: components["schemas"]["InterviewPlan"];
            /** Signature */
            signature: string;
        };
        /** SpeakRequest */
        SpeakRequest: {
            /** Text */
            text: string;
            /**
             * Voice
             * @enum {string}
             */
            voice: "Kore" | "Charon";
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
        };
        /** SystemPromptRequest */
        SystemPromptRequest: {
            settings?: components["schemas"]["InterviewSettings"];
            /**
             * System Prompt
             * @default zero_shot
             * @enum {string}
             */
            system_prompt: "zero_shot" | "few_shot" | "chain_of_thought" | "persona" | "self_critique";
            plan?: components["schemas"]["SignedPlan-Input"] | null;
        };
        /** SystemPromptResponse */
        SystemPromptResponse: {
            /** Prompt */
            prompt: string;
        };
        /** TranscriptResponse */
        TranscriptResponse: {
            /** Text */
            text: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    chat_api_interview_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_stream_api_interview_chat_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    system_prompt_api_interview_system_prompt_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SystemPromptRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemPromptResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppConfig"];
                };
            };
        };
    };
    parse_cv_api_cv_parse_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_parse_cv_api_cv_parse_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_plan_api_interview_plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignedPlan-Output"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_feedback_api_interview_feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_presets_api_presets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Preset"][];
                };
            };
        };
    };
    transcribe_answer_api_voice_transcribe_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Raw PCM: 16 kHz, mono, 16-bit little-endian, no header */
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptResponse"];
                };
            };
        };
    };
    speak_sentence_api_voice_speak_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpeakRequest"];
            };
        };
        responses: {
            /** @description Raw PCM: 24 kHz, mono, 16-bit, no header */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
