/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/interview/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_api_interview_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/interview/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat Stream */
        post: operations["chat_stream_api_interview_chat_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Config */
        get: operations["get_config_api_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AppConfig */
        AppConfig: {
            /** Models */
            models: components["schemas"]["ModelInfo"][];
            /** Default Model */
            default_model: string;
            /** Techniques */
            techniques: ("zero_shot" | "few_shot" | "chain_of_thought" | "persona" | "self_critique")[];
            /**
             * Default Technique
             * @enum {string}
             */
            default_technique: "zero_shot" | "few_shot" | "chain_of_thought" | "persona" | "self_critique";
            /** Companies */
            companies: ("Guugle" | "HeadBook" | "Instakilogram" | "Netflux" | "Amazin'" | "Goldman Sax" | "Tesler" | "Starbacks")[];
            /** Difficulties */
            difficulties: ("easy" | "medium" | "hard")[];
            /** Personas */
            personas: ("friendly" | "neutral" | "strict")[];
            default_settings: components["schemas"]["InterviewSettings"];
        };
        /** ChatMessage */
        ChatMessage: {
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Content */
            content: string;
        };
        /** ChatRequest */
        ChatRequest: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Messages */
            messages: components["schemas"]["ChatMessage"][];
            settings?: components["schemas"]["InterviewSettings"];
            /**
             * System Prompt
             * @default zero_shot
             * @enum {string}
             */
            system_prompt: "zero_shot" | "few_shot" | "chain_of_thought" | "persona" | "self_critique";
            model_settings?: components["schemas"]["ModelSettings"];
        };
        /** ChatResponse */
        ChatResponse: {
            /** Reply */
            reply: string;
            /** Blocked */
            blocked?: ("message" | "role" | "guard_error" | "leak") | null;
            /** Hint */
            hint?: ("end" | "off_topic" | "not_answered") | null;
            /** Ended */
            ended?: ("candidate_left" | "limit_reached") | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InterviewSettings */
        InterviewSettings: {
            /**
             * Company
             * @default Guugle
             * @enum {string}
             */
            company: "Guugle" | "HeadBook" | "Instakilogram" | "Netflux" | "Amazin'" | "Goldman Sax" | "Tesler" | "Starbacks";
            /**
             * Role
             * @default Software Engineer
             */
            role: string;
            /**
             * Difficulty
             * @default medium
             * @enum {string}
             */
            difficulty: "easy" | "medium" | "hard";
            /**
             * Persona
             * @default friendly
             * @enum {string}
             */
            persona: "friendly" | "neutral" | "strict";
        };
        /** ModelInfo */
        ModelInfo: {
            /** Id */
            id: string;
            /** Name */
            name?: string | null;
            /** Input Price Per M */
            input_price_per_m?: number | null;
            /** Output Price Per M */
            output_price_per_m?: number | null;
            /** Supported Parameters */
            supported_parameters?: string[] | null;
            /** Reasoning Efforts */
            reasoning_efforts?: string[] | null;
        };
        /** ModelSettings */
        ModelSettings: {
            /** Model */
            model?: string | null;
            /**
             * Reasoning Effort
             * @default low
             * @enum {string}
             */
            reasoning_effort: "minimal" | "low" | "medium" | "high";
            /**
             * Max Tokens
             * @default 1000
             */
            max_tokens: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    chat_api_interview_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_stream_api_interview_chat_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppConfig"];
                };
            };
        };
    };
}
